"""
Django settings for chatproj project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path

# --- RUTAS BASE ---
BASE_DIR = Path(__file__).resolve().parent.parent

# --- CONFIGURACIÓN GENERAL ---
SECRET_KEY = 'django-insecure-%b$t2blx+0k(14j=jv)&#)6*q6+g0zbr^^o%s*19ep7-(tz0a3'
DEBUG = True

# Permitir acceso local y en red LAN
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '*']

# --- APLICACIONES INSTALADAS ---
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Nuestras apps
    'chat',

    # Channels para WebSockets
    'channels',
]

# --- MIDDLEWARE ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --- URLS Y TEMPLATES ---
ROOT_URLCONF = 'chatproj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # carpeta de plantillas globales
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# --- APLICACIONES ASGI / WSGI ---
WSGI_APPLICATION = 'chatproj.wsgi.application'  # para peticiones HTTP normales
ASGI_APPLICATION = 'chatproj.asgi.application'  # para WebSockets (Channels)

# --- CHANNEL LAYERS ---

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    }
}



# --- BASE DE DATOS ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# --- VALIDADORES DE CONTRASEÑA ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- CONFIGURACIÓN DE IDIOMA Y ZONA HORARIA ---
LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Asuncion'  # puedes cambiar a tu zona
USE_I18N = True
USE_TZ = True

# --- ARCHIVOS ESTÁTICOS ---
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "chat" / "static",  # carpeta estática dentro de la app
]

# --- CLAVE PRIMARIA AUTOMÁTICA ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
